### ISSUE TITLE
主页更新

### ISSUE THREAD

**Issue by aeilot** [HSEFZ-technician/HSEFZ-digital-life#1]

**Comment by aeilot** [comment]
这个主页，我的想法是，先做成类似 https://www.apple.com/apps/ 的样子，但是标题要显示一整页，类似 https://firstrobotics.com.cn/

**Comment by aeilot** [comment]
网页的标题就 #EFZ 吧

**Comment by CLCK0622** [comment]
看上去不错👀
mol
